default_platform(:android)

platform :android do
  desc "Lane for Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:1048619237270:android:b986a5655f2c85129b67b7",
    firebase_cli_token: "1//03A1LBiNpbA5vCgYIARAAGAMSNwF-L9IrcadmOu70IdSQ1VS7twW9nEtzsxArbIcSBo-9cpT71kbrsCTII6ODYKFIQnRDqSFR5Og",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "mazenanter99@gmail.com",
    release_notes: "First line in fastlane"
  )
  end
end
