name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"
        working-directory: android
        bundler-cache: false

    - name: Install Bundler
      run: gem install bundler

    - name: Clean and Install Dependencies
      run: |
        cd android
        rm -rf Gemfile.lock
        bundle install --jobs 4 --retry 3

    - name: Update Fastlane and Plugins
      run: |
        cd android
        bundle exec fastlane update_plugins

    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        cd android
        bundle exec fastlane android firebase_distribution
